name: Deploy via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build site
        run: |
          npm ci
          npm run build

      - name: Upload via SSH
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ssh.chowfiyk7.service.one
          REMOTE_USER: chowfiyk7_w473616
          REMOTE_PORT: 22
          SOURCE: "dist/"
          TARGET: "/public_html/"
